version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "master"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "UTC"
    target-branch: "master"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
    labels:
      - dependencies

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "UTC"
    target-branch: "master"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(tf)"
    labels:
      - dependencies
