name: ci
on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Go fmt & test
        run: |
          go fmt ./...
          go test ./... -v
